### ISSUE TITLE
Remove baseline rechecking logic 

### ISSUE THREAD

**Issue by major** [RH-FMK/sktm#106]
The baseline rechecking logic found here should be removed: https://github.com/RH-FMK/sktm/blob/master/sktm/__init__.py#L354-L361

It has already been removed from skt: https://github.com/RH-FMK/skt/commit/f1082920ddb859ea3aeca2b66e0315c03108d214

**Comment by spbnick** [comment]
I have a patch ready in my queue for this, thanks for the issue :)

**Comment by major** [comment]
@spbnick I can send plenty more issues your way if you like these. ;)

**Comment by spbnick** [comment]
I love them, go ahead :D!

**Comment by veruu** [comment]
This was fixed in 4035c396ec5a
