### ISSUE TITLE
Name patchwork.skt_patchwork and patchwork.skt_patchwork2 properly

### ISSUE THREAD

**Issue by spbnick** [RH-FMK/sktm#11]
We don't need to repeat "patchwork" inside the "patchwork" module, we don't need to repeat "skt" inside the "skt" package, plus we better use descriptive names instead of "2" and nothing. E.g. "patchwork.XMLRPCInterface" and "patchwork.RESTInterface".

**Comment by spbnick** [comment]
We can also have the (future) parent class named "patchwork.Interface", or such.

**Comment by veruu** [comment]
There are issues #35 and #38 which provide additional new context for classes etc so closing this one
