### ISSUE TITLE
Use path manipulations instead of string concatenations

### ISSUE THREAD

**Issue by veruu** [RH-FMK/sktm#77]
Both URL and file path joins use slashes as dividers between their parts. When joining them, we need to be extra careful if the original path ends with slash or there is none. Examples:

`path/to/dir + file --> path/to/dir/file`
`path/to/dir/ + file --> path/to/dir/file`
`http://url.com/ + part --> http://url.com/part`
`http://url.com + part --> http://url.com/part`

Right now, most of the code uses string concatenation for joins, which doesn't handle any of these cases. This requires us to be extra careful about what is passed to the functions (eg. some websites don't like double slashes), which is not that simple with all the passing between different functions and objects and doesn't check user inputs either.

`os.path.join()` can deal with all these cases and works just fine with both URLs and filepaths. This allows us to simply type `os.path.join('http://url.com', 'part')` or `os.path.join(directory, filename)` (if variables are used) and not care about ending slashes anywhere.

**Comment by spbnick** [comment]
The use of `os.path.join()` for URL manipulation seems a hack for me, especially considering the different behavior on Windows (not that we plan on running skt there). So, at the very least I would like to see it not used directly, but instead have something like `sktm.misc.url_join()` which would use it. It would be more readable, and we would be able to easily replace the implementation, if necessary. Perhaps even use the urlparse library eventually.

@major, what's your take?

**Comment by major** [comment]
I'd prefer to just template the string so I know *exactly* what's going in each time. For example:

```python
url = "{}/patch/{}".format(url, patch_id)
```

I know that Patchwork is really picky about having double slashes in the URL.

**Comment by veruu** [comment]
`urlparse` doesn't handle slashes very gracefully and has the same problem, which is why I opted for `os.path`. I do agree with having a misc function that can be used everywhere and changed if needed

@major , sometimes we get URLs from command line. If the user gives you URL ending in slash, you example gets broken

**Comment by veruu** [comment]
> We could always .strip() any trailing slashes and do a substring replace on the string for double slash to single slash. That could be tossed into a common function.

If we can ensure that the `//` in `http://url.com` doesn't get replaced by a single slash, I'm fine with the solution.

**Comment by danghai** [comment]
@spbnick, could you help me explain why using `os.path.join()` for URL manipulation seems a hack?

**Comment by danghai** [comment]
@veruu I come up with a solution based on @major : 
```python
def full_join_path(url, patch):
    # Remove / trailing
    url = url.rstrip('/')
    # Remove / leading
    patch = patch.lstrip()
    full_url = "{}/patch/{}".format(url, patch)
    return full_url.rstrip('/')
```

**Comment by veruu** [comment]
@danghai this is a good start, but the function should be generic enough for joining any kind of file paths and URLs, so the part with creating a specific URL of a patch (and variable naming) needs to be changed.

I'm going to give examples for skt since that's what I have opened right now and this issue should be duplicated there as well. So for example, in `skt/__init__.py` we have `mbox_url = os.path.join(url, 'mbox')` which would lead to very unexpected results when exchanged for this function. Same with `skt/kerneltree.py`, where we have `fpath = '/'.join([self.wdir, fname])` which would be nice to get working with this function after it's implemented. These are just the most obvious examples, there is plenty of other in the code ;)

Also, you can use `.strip('/')` on the second argument, since you are removing the slash from it's beginning and then from the end of the full result, which is the end of the second argument as well.

**Comment by danghai** [comment]
@veruu . If I change `full_url = "{}/{}".format(url, patch)` the case:
`mbox_url = os.path.join(url, 'mbox')` --> `full_join_path(url, 'mbox')
`fpath = '/'.join([self.wdir, fname])`  --> `full_join_path(self.wdir, fname)`. 

> so the part with creating a specific URL of a patch (and variable naming) needs to be changed.
Could you suggest the good variable name and the function name too? I do not see any issue in creating specific URL and the patch. Could you elaborate more by example?

**Comment by veruu** [comment]
@danghai That statement works much better! :)

`URL` and `patch` as variable names is confusing for the second example you showed, because a directory and file name are passed as arguments, and that has nothing to do with URLs nor patches. The naming should be generic.

Something like `base`, `suffix` would work much better as argument names, and `join_with_slash` could work as a function name since it describes what the function actually does ( @major, @spbnick, do you guys have any better ideas?)
