### ISSUE TITLE
Fix variable names in db.py

### ISSUE THREAD

**Issue by veruu** [RH-FMK/sktm#79]
Commit 526b188714 was supposed to clean up variable names so they are more descriptive, but sometimes guessed wrong and as a result, some of `get_sourceid()` results are in variables called `patchset_id` which is very confusing.

Most of the results is correctly named as `sourceid`, which is how the rest of variables should be too.

**Comment by danghai** [comment]
@veruu It means the variable name `patchset_id` should be `patchsetid` ?

**Comment by veruu** [comment]
@danghai no. It should be `sourceid`, but only when `get_sourceid()` method is involved. There are places where `patchset_id` is the correct name, so you need to check the surroundings to make sure the change is correct.

**Comment by danghai** [comment]
`sourceid` makes me confused too because I see mostly name variable relating `id` have format such as `patchset_id`, `baserepo_id` , ...

**Comment by veruu** [comment]
@danghai I'd be okay with having it say `source_id` and prefer that kind of naming too. But we will need to rework a lot of database-related functionality soon and don't want anyone to put in too much work that might be removed later. If you want to change the naming despite this, it's okay by me.
